Fix syntax error

diff --git a/scale-image-ca b/scale-image-ca
--- a/scale-image-ca
+++ b/scale-image-ca
@@ -34,7 +34,7 @@ Title=( "--title=Scale Image(s)" )
 WindowIcon=( "--window-icon=image-x-generic" )
 Icon=( "--image=image-x-generic" )
 
-Selection=$(yad "${Title[@]}" "${WindowIcon[@]}" --list --height=350 --no-headers --column="$SELECTONE" --text="$SELECTSCALE" custom 220x176 240x340 320x200 320x240 320x480 352x288 480x320 480x800 480x854 640x350 640x480 640x960 720x400 800x600 1024x768 1152x864 1280x800 1280x1024 1366x768 1400x1050 1440x900 1600x900 1600x1050 1600x1200 1680x1050 1920x1080 1920x1200)
+Selection=$(yad "${Title[@]}" "${WindowIcon[@]}" --list --height="350" --width="250" --no-headers --column="$SELECTONE" --text="$SELECTSCALE" custom 220x176 240x340 320x200 320x240 320x480 352x288 480x320 480x800 480x854 640x350 640x480 640x960 720x400 800x600 1024x768 1152x864 1280x800 1280x1024 1366x768 1400x1050 1440x900 1600x900 1600x1050 1600x1200 1680x1050 1920x1080 1920x1200)
 
 ret="$?"
 
@@ -42,18 +42,33 @@ Selection=$(echo "$Selection" | awk -F '|' '{print $1}')
 
 if [ "$ret" = "1" ]; then
  exit
-elif [ "$ret" = "252"]; then
+elif [ "$ret" = "252" ]; then
  exit
 elif [ "$Selection" = "" ]; then
  yad "${Title[@]}" --window-icon="error" --image="error" --width="350" --wrap --text="$NORESOLUTION\n" --button=$"gtk-quit:1"
  exit 0
 fi
 
+if [ "$Selection" = "custom" ]; then
+ ScaleTo="$(yad "${WindowIcon[@]}" --entry "${Title[@]}" --width="275" --text="$PLEASEENTER\n")"
+ if [ "$?" = "1" ]; then
+  exit
+ elif [ "$?" = "252" ]; then
+  exit
+ elif [ "$ScaleTo" = "" ];then
+  yad "${Title[@]}" --window-icon="error" --image="error" --text="$NORESOLUTION" --button=$"gtk-quit"
+  exit
+ fi
+else
+ ScaleTo=$Selection
+fi
+
+
 ## Allow saving files to a different folder
 
 CurrentDirectory="$(pwd)"
 
-Destination=$(yad "${Title[@]}" "${WindowIcon[@]}" --text-align="center" --file-selection --height="450" --width="500" --directory --text="$SCALEFILE\n" --button=$"gtk-quit:3" --button=$"gtk-ok:2")
+Destination=$(yad "${Title[@]}" "${WindowIcon[@]}" --text-align="center" --file-selection --height="500" --width="700" --directory --text="$SCALEFILE\n" --button=$"gtk-quit:3" --button=$"gtk-ok:2")
 
 ret="$?"
 
@@ -65,10 +80,13 @@ elif [ "$Destination" = "" ]; then
  yad "${Title[@]}" --window-icon="error" --image="error" --width="350" --wrap --text="$NODESTINATION\n" --button=$"gtk-quit:1"
 fi
 
+echo "$CurrentDirectory"
+echo "$Destination"
+
 ## Check to see if we are overwriting files and prompt the user
 
 if [ "$CurrentDirectory" = "$Destination" ]; then
- yad "${Title[@]}" --window-icon="emblem-important" --image="emblem-important" --wrap --width="350"--text="$AORO" --button=$"gtk-cancel:7" --button=$"$OVERWRITEFILES:3" --button=$"$APPENDBUTTON:5"
+ yad "${Title[@]}" --window-icon="emblem-important" --image="emblem-important" --wrap --width="350" --text="$AORO" --button=$"gtk-cancel:7" --button=$"$OVERWRITEFILES:3" --button=$"$APPENDBUTTON:5"
  ret="$?"
 
 if [ "$ret" = "252" ]; then
@@ -84,20 +102,6 @@ fi
 progressbar () {
 tail -f /usr/bin/scale-image-ca |  yad "${Title[@]}" "${WindowIcon[@]}" "${Icon[@]}" --width="350" --wrap --no-buttons --progress --pulsate --auto-close --text="$@"
 }
-
-if [ "$Selection" = "custom" ]; then
- ScaleTo="$(yad "${WindowIcon[@]}" --entry "${Title[@]}" --width="275" --text="$PLEASEENTER\n")"
- if [ "$?" = "1" ]; then
-  exit
- elif [ "$?" = "252" ]; then
-  exit
- elif [ "$ScaleTo" = "" ];then
-  yad "${Title[@]}" --window-icon="error" --image="error" --text="$NORESOLUTION" --button=$"gtk-quit"
-  exit
- fi
-else
- ScaleTo=$Selection
-fi
 
 
 progressbar "$SCALING $TO $ScaleTo $NOW\n" &
